#!/bin/sh

case "$1" in
  start)
    echo "Starting aesdsocket"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
    echo "after start-stop-daemon -S"
    ;;
  stop)
    echo "Stopping aesdsocket"
    start-stop-daemon -K -n aesdsocket -a /usr/bin/aesdsocket
    echo "after start-stop-daemon -K"
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0


