#!/bin/sh

case "$1" in
  start)
    echo "Starting aesdsocket daemon"
    start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -d
    ;;
  stop)
    echo "Starting aesdsocket daemon"
    start-stop-daemon -K -n aesdsocket -a /usr/bin/aesdsocket -d
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0


